version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    environment:
      - REACT_APP_API_URL=http://localhost:8001
    depends_on:
      - api

  api:
    build: ./api
    ports:
      - "8001:8000"
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - CORS_ALLOW_ORIGIN=http://localhost:8000
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 