[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm run build"
dockerfilePath = "frontend/Dockerfile"

[deploy]
startCommand = "npx serve -s build"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.env]
NODE_ENV = "production"
REACT_APP_API_URL = "https://callcenterbackend-production.up.railway.app"