[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y php8.2 php8.2-curl php8.2-mbstring php8.2-xml php8.2-zip"

[deploy]
startCommand = "cd /app/api && php -S 0.0.0.0:8000 -t public"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production"
REACT_APP_API_URL = "https://callcenter-api.up.railway.app"
PHP_VERSION = "8.2" 