[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm run build"

[deploy]
startCommand = "cd frontend && npm run serve"
healthcheckPath = "/health"
healthcheckTimeout = 5
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.env]
PORT = "8000"
NODE_ENV = "production"
REACT_APP_API_URL = "https://callcenterbackend-production.up.railway.app"